/* This file was generated by syncqt. */
#ifndef QT_QTQMLCORE_VERSION_H
#define QT_QTQMLCORE_VERSION_H

#define QTQMLCORE_VERSION_STR "6.4.2"

#define QTQMLCORE_VERSION 0x060402

#endif // QT_QTQMLCORE_VERSION_H
